services:

  exam_db:
    image: postgres:15
    container_name: exam_db
    restart: always
    environment:
      POSTGRES_USER: exam_user
      POSTGRES_PASSWORD: exam_password
      POSTGRES_DB: exam_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eri-backend:
    build: .
    container_name: eri-backend
    depends_on:
      - exam_db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data: