# -------------------------
# 🔥 GLOBAL SETTINGS
# -------------------------
worker_processes auto;

events {
    worker_connections 4096;
    multi_accept on;
}

http {

    # -------------------------
    # 🔥 BASIC OPTIMIZATION
    # -------------------------
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 30s;
    keepalive_requests 10000;

    types_hash_max_size 2048;

    include       mime.types;
    default_type  application/octet-stream;

    # -------------------------
    # 🔥 RATE LIMITING (CRITICAL)
    # -------------------------

#Commented out temporarily to test load capacity. To be included in production deployment.

#    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=220r/s;

    # -------------------------
    # 🔥 UPSTREAM BACKEND POOL
    # -------------------------
    upstream eri_backend {
        least_conn;

        server eri-backend-1:8000 max_fails=3 fail_timeout=10s;
#        server eri-backend-2:8000 max_fails=3 fail_timeout=10s;

        keepalive 64;

    }

    # -------------------------
    # 🔥 SERVER CONFIG
    # -------------------------
    server {
        listen 80;

        location = /health {

            proxy_pass http://eri_backend;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header X-Upstream $upstream_addr always;

            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 30s;

            proxy_buffering off;

            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
        }

        location / {

#Termporarily commented out for load testing. Must be included in production deployment.
#            limit_req zone=api_limit burst=400;

            proxy_pass http://eri_backend;

            proxy_http_version 1.1;
            proxy_set_header Connection "";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header X-Upstream $upstream_addr always;

            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 30s;

            proxy_buffering off;

            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
            proxy_next_upstream_tries 2;
        }
    }
}