"""replace hint_open_count with answer_change_count

Revision ID: 0a1089726ab0
Revises: deb4ea18da16
Create Date: 2026-07-25 22:29:55.991274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1089726ab0'
down_revision: Union[str, Sequence[str], None] = 'deb4ea18da16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt_answers', sa.Column('answer_change_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('attempt_answers', 'hint_open_count')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.add_column('attempt_answers', sa.Column('hint_open_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('attempt_answers', 'answer_change_count')
    # ### end Alembic commands ###
