"""add graduation_year to registration_application

Revision ID: e8ad036c129f
Revises: 90e0a9efb3f9
Create Date: 2026-03-19 12:54:07.597078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8ad036c129f'
down_revision: Union[str, Sequence[str], None] = '90e0a9efb3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt_answers', sa.Column('is_special', sa.Boolean(), nullable=False))
    op.add_column('attempt_answers', sa.Column('weight_used', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('attempts', sa.Column('shuffle_seed', sa.String(), nullable=True))
    op.add_column('attempts', sa.Column('question_pool_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('registration_applications', sa.Column('graduation_year', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_applications', 'graduation_year')
    op.drop_column('attempts', 'question_pool_ids')
    op.drop_column('attempts', 'shuffle_seed')
    op.drop_column('attempt_answers', 'weight_used')
    op.drop_column('attempt_answers', 'is_special')
    # ### end Alembic commands ###
