"""season1 identity foundation

Revision ID: 5457f0fd4d64
Revises: 
Create Date: 2026-02-18 11:55:27.852812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5457f0fd4d64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'SCORING', 'FINALIZED', 'ARCHIVED', name='challenge_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('exam_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_seconds', sa.Integer(), nullable=False),
    sa.Column('is_force_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'day_number', name='uq_challenge_day_number')
    )
    op.create_table('institution_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('college', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('avg_percentile', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('participation_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('institutional_index', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('global_institution_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'college', name='uq_challenge_college')
    )
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('college', sa.String(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISQUALIFIED', name='account_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_code', name='uq_participant_code'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenge')
    )
    op.create_table('registration_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('college', sa.String(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('enrolled', sa.Boolean(), nullable=False),
    sa.Column('welcome_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('welcome_email_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'challenge_id', name='uq_registration_email_challenge'),
    sa.UniqueConstraint('participant_code', name='uq_registration_participant_code')
    )
    op.create_index(op.f('ix_registration_applications_email'), 'registration_applications', ['email'], unique=False)
    op.create_index(op.f('ix_registration_applications_participant_code'), 'registration_applications', ['participant_code'], unique=False)
    op.create_table('scoring_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('exam_day_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'MISSED', name='attempt_status_enum'), nullable=False),
    sa.Column('special_unlocked', sa.Boolean(), nullable=False),
    sa.Column('bonus_entered', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allowed_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_score', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('final_score', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('scoring_version', sa.Integer(), nullable=False),
    sa.Column('hints_used_count', sa.Integer(), nullable=False),
    sa.Column('attendance_flag', sa.Boolean(), nullable=False),
    sa.Column('start_ip', sa.String(), nullable=True),
    sa.Column('start_user_agent', sa.String(), nullable=True),
    sa.Column('last_ip', sa.String(), nullable=True),
    sa.Column('last_user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_day_id'], ['exam_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'exam_day_id', name='uq_participant_exam_day')
    )
    op.create_index('idx_attempt_challenge', 'attempts', ['challenge_id'], unique=False)
    op.create_index('idx_attempt_exam_day', 'attempts', ['exam_day_id'], unique=False)
    op.create_index('idx_attempt_participant', 'attempts', ['participant_id'], unique=False)
    op.create_table('participant_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('cumulative_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cumulative_base_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('days_completed', sa.Integer(), nullable=False),
    sa.Column('attendance_count', sa.Integer(), nullable=False),
    sa.Column('eligible_for_bonus_next_day', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'participant_id', name='uq_progress_challenge_participant')
    )
    op.create_index(op.f('ix_participant_progress_challenge_id'), 'participant_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_participant_progress_participant_id'), 'participant_progress', ['participant_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('exam_day_id', sa.UUID(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty_enum'), nullable=False),
    sa.Column('allocated_time_seconds', sa.Integer(), nullable=False),
    sa.Column('hint_text', sa.String(), nullable=True),
    sa.Column('hint_penalty_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_day_id'], ['exam_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_day_id', 'question_order', name='uq_examday_order')
    )
    op.create_table('rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentile', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('state_rank', sa.Integer(), nullable=True),
    sa.Column('institution_rank', sa.Integer(), nullable=True),
    sa.Column('ranking_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'participant_id', name='uq_challenge_participant_rank')
    )
    op.create_index('idx_rankings_challenge_global_rank', 'rankings', ['challenge_id', 'global_rank'], unique=False)
    op.create_index('idx_rankings_challenge_score', 'rankings', ['challenge_id', 'total_score'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('hint_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answer_question')
    )
    op.create_table('responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('attempt_answers')
    op.drop_index('idx_rankings_challenge_score', table_name='rankings')
    op.drop_index('idx_rankings_challenge_global_rank', table_name='rankings')
    op.drop_table('rankings')
    op.drop_table('questions')
    op.drop_index(op.f('ix_participant_progress_participant_id'), table_name='participant_progress')
    op.drop_index(op.f('ix_participant_progress_challenge_id'), table_name='participant_progress')
    op.drop_table('participant_progress')
    op.drop_index('idx_attempt_participant', table_name='attempts')
    op.drop_index('idx_attempt_exam_day', table_name='attempts')
    op.drop_index('idx_attempt_challenge', table_name='attempts')
    op.drop_table('attempts')
    op.drop_table('scoring_versions')
    op.drop_index(op.f('ix_registration_applications_participant_code'), table_name='registration_applications')
    op.drop_index(op.f('ix_registration_applications_email'), table_name='registration_applications')
    op.drop_table('registration_applications')
    op.drop_table('participants')
    op.drop_table('institution_rankings')
    op.drop_table('exam_days')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('challenges')
    # ### end Alembic commands ###
