# ======================================================
# CONNECTIONS
# ======================================================

listen_addresses = '*'

max_connections = 300
superuser_reserved_connections = 3

# ======================================================
# MEMORY
# ======================================================

shared_buffers = 1536MB
effective_cache_size = 4GB
work_mem = 8MB
maintenance_work_mem = 256MB

# ======================================================
# WAL
# ======================================================

wal_buffers = 16MB

checkpoint_timeout = 15min
checkpoint_completion_target = 0.9

max_wal_size = 4GB
min_wal_size = 1GB

# ======================================================
# PARALLELISM
# ======================================================

max_worker_processes = 6
max_parallel_workers = 6
max_parallel_workers_per_gather = 2

# ======================================================
# QUERY PLANNER
# ======================================================

random_page_cost = 1.1
effective_io_concurrency = 200

# ======================================================
# SAFETY
# ======================================================

idle_in_transaction_session_timeout = 30000
statement_timeout = 60000

# ======================================================
# EXTENSIONS
# ======================================================

shared_preload_libraries = 'pg_stat_statements'
track_io_timing = on
pg_stat_statements.track = all

password_encryption = scram-sha-256