# app/core/error_codes.py

class ErrorCode:
    # AUTH
    UNAUTHORIZED = "UNAUTHORIZED"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # ATTEMPT
    ALREADY_COMPLETED = "ALREADY_COMPLETED"
    WINDOW_CLOSED = "WINDOW_CLOSED"
    FORCE_LOCKED = "FORCE_LOCKED"
    INVALID_ATTEMPT = "INVALID_ATTEMPT"
    ATTEMPT_NOT_FOUND = "ATTEMPT_NOT_FOUND"
    ATTEMPT_NOT_ACTIVE = "ATTEMPT_NOT_ACTIVE"
    ATTEMPT_EXPIRED = "ATTEMPT_EXPIRED"

    # QUESTION
    QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"
    INVALID_QUESTION_ACCESS = "INVALID_QUESTION_ACCESS"

    # SYSTEM
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

    # ADD under GENERAL / SYSTEM
    FORBIDDEN = "FORBIDDEN"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    BAD_REQUEST = "BAD_REQUEST"